### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by deadline-cxn** [Badading/The_Gate#3]
Hi, S_Coder here. Ya'll came onto my server the other night. Well I was going through configs today to shore up some things, and I noticed that The Gate files aren't using the correct path separator. I will show you what I mean.

In the plugins top level folder, it created:
The_Gate\GateSaveFile.sqlite

And inside The_Gate folder, it created:
\GateSaveFile.sqlite

See images below.

![TheGate1Capture](https://user-images.githubusercontent.com/4054569/78877347-b5725d00-7a1e-11ea-9db1-6b7a34a07e4b.PNG)

![TheGate2Capture](https://user-images.githubusercontent.com/4054569/78877354-b73c2080-7a1e-11ea-830d-43bd77fc5591.PNG)

Note: I am running the latest paper server on Linux. I suspect the reason this is happening is due to the way you're calling the path  separators. ie; Windows type of path separators, and Linux doesn't play nicely with those.

I hope this helps make your plugin better!

S_Coder
sethcoder.com:25565

**Comment by deadline-cxn** [comment]
One more thing to consider. I would recommend that if you're going to fix this, then you put in detection of that file, then write it into the proper location into the plugin and then remove the file. That way if people have been using it, they won't have to worry about their data being lost.

**Comment by EndMy5uffering** [comment]
Fixed in version 0.1.7-5.9
